stages:
  - test

test-linux:
  stage: test
  image: paritytech/ci-linux:production
  script:
    - rustup target add wasm32-unknown-unknown +nightly-2020-09-30
    - rustup show
    - cargo --version
    - sccache -s
    - time cargo test --workspace --locked --release --verbose --features runtime-benchmarks
