[package]
name = "chainx"
version = "2.0.9"
authors = ["The ChainX Authors"]
edition = "2018"
description = "Fully Decentralized Interchain Crypto Asset Management on Polkadot"

[dependencies]
cli = { package = "chainx-cli", path = "cli" }

[target.'cfg(target_arch="x86_64")'.dependencies]
cli = { package = "chainx-cli", path = "cli", features = ["wasmtime"] }

[patch.crates-io]
sc-authority-discovery = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-basic-authorship = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-chain-spec = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-cli = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-client-api = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-client-db = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-consensus = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-consensus-babe = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-consensus-babe-rpc = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-consensus-epochs = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-consensus-slots = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-consensus-uncles = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-executor = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-finality-grandpa = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-finality-grandpa-rpc = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-finality-grandpa-warp-sync = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-informant = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-keystore = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-network = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-offchain = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-rpc = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-rpc-api = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-service = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-sync-state-rpc = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-telemetry = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sc-transaction-pool = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }

sp-api = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-application-crypto = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-arithmetic = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-authority-discovery = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-authorship = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-block-builder = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-blockchain = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-consensus = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-consensus-babe = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-core = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-finality-grandpa = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-inherents = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-io = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-keystore = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-offchain = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-rpc = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-runtime = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-runtime-interface = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-session = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-staking = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-state-machine = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-std = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-storage = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-timestamp = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-tracing = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-transaction-pool = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-trie = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
sp-version = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }

frame-benchmarking = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
frame-benchmarking-cli = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
frame-executive = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
frame-support = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
frame-system = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
frame-system-benchmarking = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
frame-system-rpc-runtime-api = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }

substrate-frame-rpc-system = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
substrate-wasm-builder = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }

pallet-authorship = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-babe = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-balances = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-bounties = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-collective = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-democracy = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-elections-phragmen = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-grandpa = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-identity = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-im-online = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-indices = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-membership = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-multisig = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-offences = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-proxy = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-randomness-collective-flip = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-scheduler = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-session = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-sudo = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-timestamp = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-tips = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-transaction-payment = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-transaction-payment-rpc = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-treasury = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }
pallet-utility = { git = "https://github.com/chainx-org/substrate", branch = "tracing-rotation" }

[workspace]
members = [
  "cli",
  "executor",
  "primitives",
  "primitives/assets-registrar",
  "primitives/gateway/bitcoin",
  "primitives/gateway/common",
  "primitives/genesis-builder",
  "primitives/io",
  "primitives/mining/common",
  "primitives/mining/staking",
  "primitives/protocol",
  "primitives/rpc",
  "primitives/runtime",
  "rpc",
  "runtime/chainx",
  "runtime/common",
  "runtime/dev",
  "runtime/malan",
  "service",
  "xpallets/assets",
  "xpallets/assets/rpc",
  "xpallets/assets/rpc/runtime-api",
  "xpallets/assets-registrar",
  "xpallets/dex/spot",
  "xpallets/dex/spot/rpc",
  "xpallets/dex/spot/rpc/runtime-api",
  "xpallets/gateway/bitcoin/v1",
  "xpallets/gateway/common",
  "xpallets/gateway/common/rpc",
  "xpallets/gateway/common/rpc/runtime-api",
  "xpallets/gateway/records",
  "xpallets/gateway/records/rpc",
  "xpallets/gateway/records/rpc/runtime-api",
  "xpallets/genesis-builder",
  "xpallets/mining/asset",
  "xpallets/mining/asset/rpc",
  "xpallets/mining/asset/rpc/runtime-api",
  "xpallets/mining/staking",
  "xpallets/mining/staking/rpc",
  "xpallets/mining/staking/rpc/runtime-api",
  "xpallets/support",
  "xpallets/system",
  "xpallets/transaction-fee",
  "xpallets/transaction-fee/rpc",
  "xpallets/transaction-fee/rpc/runtime-api",
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
panic = "unwind"

[features]
runtime-benchmarks = ["cli/runtime-benchmarks"]
