[package]
name = "chainx"
version = "2.0.8"
authors = ["The ChainX Authors"]
edition = "2018"
description = "Fully Decentralized Interchain Crypto Asset Management on Polkadot"

[dependencies]
cli = { package = "chainx-cli", path = "cli" }

[target.'cfg(target_arch="x86_64")'.dependencies]
cli = { package = "chainx-cli", path = "cli", features = [ "wasmtime" ] }

[patch.crates-io]
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-cli = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-client-api = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-client-db = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-consensus = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-executor = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-informant = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-keystore = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-offchain = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-rpc = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-service = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }

sp-api = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-consensus = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-inherents = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-io = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-keystore = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-offchain = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-rpc = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-session = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-staking = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-std = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-storage = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-tracing = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-trie = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
sp-version = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
frame-executive = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
frame-support = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
frame-system = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }

substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }

pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-authorship = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-babe = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-balances = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-collective = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-democracy = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-identity = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-indices = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-membership = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-offences = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-session = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }
pallet-utility = { git = "https://github.com/paritytech/substrate", rev = "e6d498a901706c9753cb96de4bec5401143be8f2" }

[workspace]
members = [
    "cli",
    "executor",
    "primitives",
    "primitives/assets-registrar",
    "primitives/gateway/bitcoin",
    "primitives/gateway/common",
    "primitives/genesis-builder",
    "primitives/io",
    "primitives/logging",
    "primitives/mining/common",
    "primitives/mining/staking",
    "primitives/protocol",
    "primitives/rpc",
    "primitives/runtime",
    "rpc",
    "runtime/chainx",
    "runtime/common",
    "runtime/dev",

    "xpallets/assets",
    "xpallets/assets/rpc",
    "xpallets/assets/rpc/runtime-api",
    "xpallets/assets-registrar",
    "xpallets/dex/spot",
    "xpallets/dex/spot/rpc",
    "xpallets/dex/spot/rpc/runtime-api",
    "xpallets/gateway/bitcoin",
    "xpallets/gateway/common",
    "xpallets/gateway/common/rpc",
    "xpallets/gateway/common/rpc/runtime-api",
    "xpallets/gateway/records",
    "xpallets/gateway/records/rpc",
    "xpallets/gateway/records/rpc/runtime-api",
    "xpallets/genesis-builder",
    "xpallets/mining/asset",
    "xpallets/mining/asset/rpc",
    "xpallets/mining/asset/rpc/runtime-api",
    "xpallets/mining/staking",
    "xpallets/mining/staking/rpc",
    "xpallets/mining/staking/rpc/runtime-api",
    "xpallets/support",
    "xpallets/system",
    "xpallets/transaction-fee",
    "xpallets/transaction-fee/rpc",
    "xpallets/transaction-fee/rpc/runtime-api",
]

[profile.release]
panic = "unwind"

[features]
runtime-benchmarks = ["cli/runtime-benchmarks"]
