[package]
name = "xp-logging"
version = "2.0.9"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
log = { version = "0.4.14", default-features = false }

[features]
default = ["std"]
std = ["log/std"]
