[package]
name = "xpallet-gateway-bitcoin-offchain"
version = "2.0.5"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive"], default-features = false }
hex = { version = "0.4", default-features = false }
lite-json = { version = "0.1", default-features = false }
serde = { version = "1.0", optional = true }

# Substrate primitives
sp-application-crypto = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }

# Substrate pallets
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
pallet-session = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../../primitives", default-features = false }
xp-gateway-bitcoin = { path = "../../../../primitives/gateway/bitcoin", default-features = false }
xp-logging = { path = "../../../../primitives/logging", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../../assets", default-features = false }
xpallet-gateway-bitcoin = { path = "../", default-features = false }
xpallet-gateway-common = { path = "../../common", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "master", default-features = false }

[dev-dependencies]
sp-keystore = "0.8.0"
pallet-balances = "2.0.0"
xpallet-assets = { path = "../../../assets" }
xpallet-assets-registrar = { path = "../../../assets-registrar" }
xpallet-gateway-common = { path = "../../common" }
xpallet-gateway-records = { path = "../../records" }

[features]
default = ["std"]
std = [
    "codec/std",
    "hex/std",
    "lite-json/std",
    "serde",
    # Substrate primitives
    "sp-application-crypto/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrate pallets
    "frame-support/std",
    "frame-system/std",
    "pallet-session/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-gateway-bitcoin/std",
    "xp-logging/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-gateway-bitcoin/std",
    "xpallet-gateway-common/std",
    # light-bitcoin
    "light-bitcoin/std",
]